### ISSUE TITLE
Custom resource should provide resource requests and limits configuration

### ISSUE THREAD

**Issue by ooteniya1** [konveyor/tackle-operator#104]
The cr for installing the Tackle Toolkit is very basic. In a multitenant environment where LimitRanges are defined, most of the components of the toolkit fail due to resource issues/constraints.

apiVersion: tackle.io/v1alpha1
kind: Tackle
metadata:
  finalizers:
    - tackles.tackle.io/finalizer
  generation: 1
  name: tackle
  namespace: tackle

The operator should add parameters to add resource requests and limits for each of the components in the toolkit.

**Comment by carlosthe19916** [comment]
Hello @ooteniya1 , my understanding is that you have applied a workaround to solve this problem right? May I ask you what are the values for Memory and CPU you have set? And if you experienced slowiness with certain values of memory or CPU?

I mean, in your workaround what values did you set here?

```
resources:            
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "1"
    memory: "512Mi"
```
